# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisprova', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prova_selecionada',
            old_name='turma',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='nome_aluno',
            new_name='author',
        ),
    ]
