# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisprova', '0003_auto_20171015_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='prova_selecionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisprova.Prova_Selecionada'),
        ),
    ]
